### ISSUE TITLE
Tweaks to NERSC CI needed for TXPipe

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/desc-continuous-integration#9]
Hi Stuart, Heather,

Many thanks for the NERSC CI instructions, which look like they must have been a lot of work to figure out!

I had to make two small changes to get this to work for TXPipe:
- I needed to add   `GIT_SUBMODULE_STRATEGY: recursive` to the `variables` in the target repo's `.gitlab-ci.yml` because we use submodules for some dependencies. Probably worth putting this in by default since it shouldn't hurt if unused.
- I needed to change `--form ref=main` to `master` in the mirror repo's `.gitlab-ci.yml` - might be worth mentioning something in the docs.

Cheers,
Joe

**Comment by heather999** [comment]
both of these seem fine. 
I'd like to test what happens when GIT_SUBMODULE_STRATEGY  is set to recursive for repos without submodules.  Including some short comment in the .gitlab-ci.yml might be helpful.

I have been wondering about promoting migration to `main` rather than `master` as the primary branch, though understandably this may be difficult for repos that have developers who may have the code locally.  This probably isn't the place to deal with that issue. Easy enough to just mention how to deal with primary branch names other than `'main`

**Comment by stuartmcalpine** [comment]
Thanks Joe for the comments.

I have tried to make it a bit clearer that ``main`` is the default branch in the CI files and how to change it (Also the GITHUB_SOURCE_BRANCH var in the yml file wasn't actually being called in the curl command so I've updated that).

I've also added a not in the docs about GIT_SUBMODULE_STRATEGY: recursive.

Thanks again :)
